{
    "version": 1,
    "Resources": [
      {
        "TargetService": {
          "Type": "AWS::ECS::Service",
          "Properties": {
            "TaskDefinition": "<TASK_DEFINITION>",
            "LoadBalancerInfo": {
              "ContainerName": "Container-app-Security",
              "ContainerPort": 5000
            }
          }
        }
      }
    ]
  }