apiVersion: v1
kind: Service
metadata:
  name: entrenamiento
  labels:
    app: entrenamiento
spec:
  selector:
    app: entrenamiento

  ports:
    - port: 5000
      targetPort: 5000

  type: LoadBalancer

