apiVersion: v1
kind: Service
metadata:
  name: entrenamiento
  labels:
    app: entrenamiento
spec:
  type: ClusterIP
  selector:
    app: entrenamiento

  ports:
    - port: 80
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: entrenamiento-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: a1b7563a0858f4f71b48c713a5de8c20-991979942.us-east-1.elb.amazonaws.com
      http:
        paths:
          - path: /entrenamiento
            pathType: Prefix
            backend:
              service:
                name: entrenamiento
                port:
                  number: 80
